language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
install:
    - "python setup.py develop"
    - "pip install {{cookiecutter.project_slug}}[tests] coveralls pylama"
    # manually install wheel for deployment
    - "pip install wheel"
script:
    - "py.test -v --cov {{cookiecutter.project_slug}} tests/"
    - "pylama"
after_success:
    - coveralls

deploy:
    provider: pypi
    user: {{cookiecutter.pypi_username}}
    password:
        secure: "run travis encrypt --add deploy.password"
    on:
        tags: true
        all_branches: true
        repo: {{cookiecutter.github_username}}/{{cookiecutter.project_slug}}
    distributions: "sdist bdist_wheel"
