language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
install:
    - "pip install -r requirements-test.txt"
    - "python setup.py develop"
    - "pip install {{cookiecutter.pypi_name}}[tests] coveralls wheel"
script:
    - "py.test -v --cov {{cookiecutter.package_name}} tests/"
    - "pylama"
    - "pyroma ."
after_success:
    - coveralls

deploy:
    provider: pypi
    user: {{cookiecutter.pypi_username}}
    password:
        secure: "run travis encrypt --add deploy.password"
    on:
        tags: true
        all_branches: true
        repo: ClearcodeHQ/{{cookiecutter.pypi_name}}
    distributions: "sdist bdist_wheel"
